blank_issues_enabled: false
contact_links:
  - name: Polygon CDK Docs
    url: https://docs.hermez.io
    about: Official Polygon CDK Documentation
  - name: Telegram Group
    url: https://t.me/PolygonHermezChat
    about: Official Polygon CDK Telegram Group
  - name: Discord Community
    url: https://discord.gg/0xPolygon
    about: Official Polygon CDK Discord Community
